ALTER TABLE public.ventas 
ADD COLUMN total NUMERIC(10, 2) NOT NULL DEFAULT 0.00;
ALTER TABLE public.detalles_venta 
ADD COLUMN precio_unitario NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
ADD COLUMN subtotal NUMERIC(10, 2) NOT NULL DEFAULT 0.00;